### ISSUE TITLE
Cabal exit cleanup

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/cabal#16]
When Illthorn + Cabal are used, and the user types `exit`, Illthorn drops, but Cabal does not detect the state change and remains connected.  Any scripts that are running at the time are, of course, still running.

`quit` as a synonym either does not exist or is not functioning.

If the intent is to allow someone to quickly exit an FE but leave the scripts running, perhaps another keyword could be chosen.  I'd question that intent as it would seem to too easily lead to inadvertent unattended scripting.

**Comment by ondreian** [comment]
That's weird:
https://github.com/elanthia-online/cabal/blob/master/lib/client.rb#L4-L7

**Comment by OSXLich-Doug** [comment]
Yeah, weird.  Might be macOS thing, but. . . 

![image](https://user-images.githubusercontent.com/17682675/103331327-44def680-4a1a-11eb-874e-f0bcbf6ed5d0.png)

Modified to add - probably GTK.  Seems to work ok with non-gui scripts via `exit`.

**Comment by OSXLich-Doug** [comment]
Closing this - it appears this is a behavior only exhibited by a few gui-based scripts that do not die cleanly (narost / xnarost so far).  I'll dig around and see if I can find exactly why and submit changes to the scripts rather than here.
