### ISSUE TITLE
Game.close() and GTK Script exits

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/cabal#21]
ISSUE - Present logic for Game.close then script.kill does not permit GTK scripts to close prior to kernel exit.  This results in hangs, requiring hard interrupt to close and frequently causing kernel crash if the script is caught at exactly the right time.

FIX - move script.kill procs from cabal.rb to client.rb, after 'exit' is detected and ahead of issuing Game.close()

SUGGESTED IMPROVEMENT - sleep for a heartbeat (0.1) to permit all settings / vars to save 
 - remove unnecessary Game.close in cabal.rb (gets called in client.rb)

**Comment by ondreian** [comment]
> SUGGESTED IMPROVEMENT - sleep for a heartbeat (0.1) to permit all settings / vars to save

settings are no longer cached in memory and persisted as quickly as possible to disk

**Comment by ondreian** [comment]
This should be fixed in master now, gtk no longer is in core and scripts are shut down before the game_sock & client_sock
